### ISSUE TITLE
display_df function referenced but not defined

### ISSUE THREAD

**Issue by leifulstrup** [nlp-with-transformers/notebooks#7]
**Describe the bug**
There is a reference to a function display_df(df.T, header=None) but the dsiplay_df function is not defined in the notebook.

It needs to perform something like this (or a better-written version of this):

def display_df(df, header=True):
  if header:
    return df
  else:
    df.columns = ["" for col in df.columns]
    return df

**Comment by lewtun** [comment]
Hey @leifulstrup, thanks for opening the issue! 

The `display_df()` function is defined in the `utils.py` module [here](https://github.com/nlp-with-transformers/notebooks/blob/05c26c35af83529ac110841af5ebba58727120c3/utils.py#L57). That's why we have a cell like

```python
from utils import *
setup_chapter()
```

at the top of each notebook. We recommend either running the notebook from a clone of this repo or running this line if you're on Colab / Kaggle etc:

```python
!git clone https://github.com/nlp-with-transformers/notebooks.git
%cd notebooks
from install import *
install_requirements()
```

Out of curiosity, what platform are you using to run the notebook?

cc @lvwerra

**Comment by leifulstrup** [comment]
Serves me right for not starting with that in my notebook. I was following along the book and the example notebook in my own colab notebook typing commands in to get a better feel and didn't include that at the start.  Thank you. 

The book and the code examples are terrific.

**Comment by lewtun** [comment]
Thanks for the context @leifulstrup - that helps us understand how we can improve :) We've decided to remove usage of this function in #8, so hopefully this won't be a problem for future readers as well!
